### ISSUE TITLE
responseType node is generated as category node in the output

### ISSUE THREAD

**Issue by PritiVishwakarma97** [bhagatabhijeet/capgen#4]

**Comment by bhagatabhijeet** [comment]
@PritiVishwakarma97 changed the bug title to 'responseType....' as there is no resourceType field in in XSD http://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2-os.html

**Comment by bhagatabhijeet** [comment]
resolved commit 2baf289308d09236ca28c3d29a3f32ada2b5ac37
