### ISSUE TITLE
Circle node under area node is generated as polygon node

### ISSUE THREAD

**Issue by PritiVishwakarma97** [bhagatabhijeet/capgen#5]
Circle node is generated as polygon node
Json:-
` {
          areaDesc: "Circle area",
          circle:["32.9525,-115.5527 0"],
          altitude: "1234ft"
      }`

XML:-
`<area>
      <areaDesc>Circle area</areaDesc>
      <polygon>32.9525,-115.5527 0</polygon>
      <altitude>1234ft</altitude>
</area>`

**Comment by bhagatabhijeet** [comment]
resolved in https://github.com/bhagatabhijeet/capgen/releases/tag/1.0.8 🏁
