### ISSUE TITLE
Restriction node is missing for alert parent node 

### ISSUE THREAD

**Issue by PritiVishwakarma97** [bhagatabhijeet/capgen#6]
Restriction node is missing for alert parent node

![Issue6](https://user-images.githubusercontent.com/47020813/107743336-bce94d80-6d36-11eb-86a0-21c8c1a8e8fb.png)

**Comment by bhagatabhijeet** [comment]
resolved in https://github.com/bhagatabhijeet/capgen/releases/tag/1.0.8 🏁
