### ISSUE TITLE
event code node is not generated according to CAP 1.2

### ISSUE THREAD

**Issue by PritiVishwakarma97** [bhagatabhijeet/capgen#7]
event code node is not generated according to CAP 1.2
Expected:- 

![issue7](https://user-images.githubusercontent.com/47020813/107744488-c5db1e80-6d38-11eb-97a7-86d5e8590ec1.png)

Actual: - 

![issue7-1](https://user-images.githubusercontent.com/47020813/107744545-e6a37400-6d38-11eb-83cc-e7198272324a.png)

**Comment by bhagatabhijeet** [comment]
resolved in https://github.com/bhagatabhijeet/capgen/releases/tag/1.0.8 🏁
